"""Higher-order multi-cumulant factor analysis (HOFA) in Python."""

from ._types import AdaptiveResult, FactorResult, PortfolioResult, SelectionResult, SimulationResult
from .adaptive import Adaptive_HFA, adaptive_hfa
from .estimators import (
    M2_gmm,
    M2_mle,
    M2_pca,
    M3_als,
    M3_gmm,
    M4_als,
    m2_gmm,
    m2_mle,
    m2_pca,
    m3_als,
    m3_gmm,
    m4_als,
)
from .moments import (
    c4_to_m4,
    c4m,
    direct_nonlinear_shrinkage,
    expected_utility_objective,
    fourth_cumulant_matrix,
    fourth_moment_matrix,
    jmca,
    linear_identity_shrinkage,
    m2m,
    m3m,
    m4_to_c4,
    m4m,
    modified_var_objective,
    portfolio_moments_independent,
    portfolio_moments_matrix,
    super_diag,
    third_moment_matrix,
    trace_ratio,
    variable_moment,
)
from .portfolio import Portfolio_IC, Portfolio_PC, portfolio_ic, portfolio_pc
from .projection import project
from .selection import M2_select, M3_select, M4_select, m2_select, m3_select, m4_select
from .simulation import dgp1, dgp2, hofa_DGP1, hofa_DGP2, sgt_moment, sgt_rvs

__all__ = [
    "AdaptiveResult",
    "FactorResult",
    "PortfolioResult",
    "SelectionResult",
    "SimulationResult",
    "adaptive_hfa",
    "Adaptive_HFA",
    "m2_select",
    "m3_select",
    "m4_select",
    "M2_select",
    "M3_select",
    "M4_select",
    "m2_pca",
    "m2_mle",
    "m2_gmm",
    "m3_gmm",
    "m3_als",
    "m4_als",
    "M2_pca",
    "M2_mle",
    "M2_gmm",
    "M3_gmm",
    "M3_als",
    "M4_als",
    "m2m",
    "m3m",
    "m4m",
    "c4m",
    "third_moment_matrix",
    "fourth_moment_matrix",
    "fourth_cumulant_matrix",
    "c4_to_m4",
    "m4_to_c4",
    "super_diag",
    "trace_ratio",
    "variable_moment",
    "jmca",
    "linear_identity_shrinkage",
    "direct_nonlinear_shrinkage",
    "portfolio_moments_independent",
    "portfolio_moments_matrix",
    "modified_var_objective",
    "expected_utility_objective",
    "portfolio_ic",
    "portfolio_pc",
    "Portfolio_IC",
    "Portfolio_PC",
    "project",
    "sgt_rvs",
    "sgt_moment",
    "dgp1",
    "dgp2",
    "hofa_DGP1",
    "hofa_DGP2",
]

__version__ = "0.1.0"
